server:
  port: 5000

  servlet:
    jsp:
      init-parameters:
        development: true
       
  
spring: 
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
        
  datasource:
    url: jdbc:mysql://awseb-e-3iyg4m23ym-stack-awsebrdsdatabase-dnhmc35lvxah.cp66ubjknwwd.ap-northeast-2.rds.amazonaws.com/ebdb
    username: ebroot
    password: dlekdlek6523

  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: dabi9365@gmail.com
    password: fumcsybfyadnuups
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
 